name: auto approve
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dmill-pr-bot[bot]'
    steps:
      - name: generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          app_id: ${{ secrets.RENOVATE_APP_ID }}
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
