name: ci
on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]
jobs:
  c1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ github.event.pull_request.title }}" | grep -Eq "^\[.+\/.+\] EN-[0-9]+ " || exit 1;
