name: ci
on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]
jobs:
  c1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ github.event.pull_request.title }}" | grep -Eq "^\[.+\/.+\] EN-[0-9]+ " || exit 1;
  c2:
    runs-on: ubuntu-latest
    outputs:
      appfiles: ${{ steps.changes.outputs.appfiles }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: changes
        run: |
          echo "::set-output name=appfiles::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '(values.yaml|application.yaml)$' | xargs)"
  c3:
    runs-on: ubuntu-latest
    needs: c2
    if: ${{needs.c2.outputs.appfiles}}
    steps:
      - uses: actions/checkout@v2
      - env:
          CHANGED_FILES: "${{needs.c2.outputs.appfiles}}"
        run: ./.github/scripts/yamllint.sh
